version: "3"
services:
  web:
    image: nginx
    volumes:
    - ./src:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: next.communityrevolution.co.uk
networks:
  default:
    external:
      name: nginx-proxy